services:
  mysqldb:
    container_name: mysqldb
    restart: always
    image: mysql:9.0.1
    volumes:
      - ./db:/var/lib/mysql
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MYSQL_DATABASE: shop
      MYSQL_ROOT_PASSWORD: admin_password
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    networks:
      - my-network
  redisdb:
    container_name: redisdb
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my-network
  spring-server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
      - redisdb
    ports:
      - "8080:8080"
    networks:
      - my-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/shop?allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin_password
      SPRING_DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
      SPRING_DATA_REDIS_HOST: redisdb
      SPRING_DATA_REDIS_PORT: 6379

networks:
  my-network:
    name: my-network
    driver: bridge